# Generated by Django 2.0.2 on 2018-03-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlaCarteDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BuffetMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OccursAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('visited_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('system', models.IntegerField(choices=[(1, 'Ala carte'), (2, 'Buffet')])),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='review',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='score',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='property_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='serving',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving', to='collection.Restaurant'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='collection.Restaurant'),
        ),
        migrations.AddField(
            model_name='occursat',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurs_at', to='collection.Serving'),
        ),
        migrations.AddField(
            model_name='buffetmenu',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffet_menu', to='collection.Serving'),
        ),
        migrations.AddField(
            model_name='alacartedish',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alacarte_dish', to='collection.Serving'),
        ),
    ]
