# Generated by Django 2.0.2 on 2018-03-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_review_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alacartedish',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alacarte_dishes', to='collection.Serving'),
        ),
        migrations.AlterField(
            model_name='buffetmenu',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffet_menus', to='collection.Serving'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='collection.Restaurant'),
        ),
    ]
