# Generated by Django 2.0.2 on 2018-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20180407_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_datetime',
            new_name='timestamp',
        ),
    ]
