# Generated by Django 2.0.2 on 2018-04-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20180411_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='serving',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.Serving'),
            preserve_default=False,
        ),
    ]
